import $ from 'jquery'

$(document).ready(thumbnailSelectionInit)

function thumbnailSelectionInit () {
  var inputField = $('input#thumbnail_form_thumbnail_upload')
  var uploadedThumbnail = $('div#uploaded-thumbnail-image')
  var autoGeneratedThumbnail = $('div#auto-generated-thumbnail-image')
  var thumbnailUploadRadio = $('input#thumbnail_form_thumbnail_selection_uploaded_image')
  var thumbnailUploadLabel = $('label[for="thumbnail_form_thumbnail_selection_uploaded_image"]')
  var autoThumbnailRadio = $('input#thumbnail_form_thumbnail_selection_auto_generated')
  var autoThumbnailLabel = $('label[for="thumbnail_form_thumbnail_selection_auto_generated"]')

  if (uploadedThumbnail.length === 0) {
    thumbnailUploadRadio.attr('disabled', true)
    thumbnailUploadLabel.attr('class', 'text-muted')
  }

  if (autoGeneratedThumbnail.length === 0) {
    autoThumbnailRadio.attr('disabled', true)
    autoThumbnailLabel.attr('class', 'text-muted')
  }

  inputField.change(function () {
    var fileName = $(this).val()
    if (fileName.length) {
      thumbnailUploadRadio.attr('disabled', false)
      thumbnailUploadRadio.prop('checked', true)
      thumbnailUploadLabel.attr('class', '')
    }
  })
}
