inherit_gem:
  niftany: niftany_rubocop.yml

inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'config/routes.rb'
    - 'spec/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'

RSpec/ExampleLength:
  Enabled:
    false

RSpec/MultipleExpectations:
  Enabled:
    false

RSpec/EmptyLineAfterSubject:
  Exclude:
    - 'spec/factories/work_versions.rb'
