inherit_gem:
  niftany: niftany_rubocop.yml

inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6.6
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/views/catalog/index.json.jbuilder'
    - 'config/routes.rb'
    - 'config/environments/production.rb'
    - 'config/environments/development.rb'
    - 'spec/**/*'

Rails/FilePath:
  EnforcedStyle: arguments

Rails/ApplicationController:
  Exclude:
    - 'app/controllers/api/v1/rest_controller.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/integration/**/*'

RSpec/EmptyLineAfterSubject:
  Exclude:
    - 'spec/factories/work_versions.rb'

RSpec/LeakyConstantDeclaration:
  Exclude:
    - 'spec/models/permissions_builder_spec.rb'
    - 'spec/lib/healthchecks/queue_latency_check_spec.rb'

RSpec/ExpectActual:
  Exclude:
    - 'spec/integration/qa/routing_spec.rb'

RSpec/AnyInstance:
  Enabled: false
