inherit_gem:
  niftany: niftany_rubocop.yml

inherit_from:
  - .rubocop_todo.yml

Naming/VariableNumber:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/controllers/dashboard/catalog_controller.rb'
    - 'app/views/catalog/index.json.jbuilder'
    - 'config/routes.rb'
    - 'config/environments/production.rb'
    - 'config/environments/development.rb'
    - 'spec/**/*'
    - 'lib/tasks/**/*'
    - 'app/reports/**/*'
    - 'spec/reports/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/models/user.rb'
    - 'app/services/doi_service.rb'
    - 'app/services/authorship_migration/work_version_creation_migration.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/models/work_version.rb'

Rails/DynamicFindBy:
  Exclude:
    - 'spec/models/file_resource_spec.rb'

Rails/FilePath:
  EnforcedStyle: arguments

Rails/ApplicationController:
  Exclude:
    - 'app/controllers/api/v1/rest_controller.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/api_token.rb'
    - 'app/services/migrate_collection_ids.rb'
    - 'app/services/doi_service.rb'
    - 'spec/services/doi_service_spec.rb'
    - 'spec/services/authorship_migration/collection_authorship_position_fix_spec.rb'

Rails/OutputSafety:
  Exclude:
    - 'app/components/base_metadata_component.rb'
    - 'app/decorators/resource_decorator.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/integration/**/*'
    - 'spec/system/**/*'
    - 'spec/lib/tasks/**/*'

RSpec/DescribedClass:
  Exclude:
    - 'spec/lib/omniauth/strategies/azure_oauth_spec.rb'

RSpec/RepeatedExampleGroupBody:
  Exclude:
    - 'spec/lib/omniauth/strategies/azure_oauth_spec.rb'

RSpec/EmptyLineAfterSubject:
  Exclude:
    - 'spec/factories/work_versions.rb'

RSpec/LeakyConstantDeclaration:
  Exclude:
    - 'spec/models/permissions_builder_spec.rb'
    - 'spec/lib/healthchecks/queue_latency_check_spec.rb'
    - 'spec/system/active_job_system_spec.rb'
    - 'spec/models/concerns/all_dois_spec.rb'
    - 'spec/models/concerns/null_object_pattern_spec.rb'

RSpec/ExpectActual:
  Exclude:
    - 'spec/integration/qa/routing_spec.rb'
    - 'spec/routes/dashboard/actors_routing_spec.rb'

RSpec/AnyInstance:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MessageSpies:
  Exclude:
    - 'spec/jobs/doi_minting_job_spec.rb'
    - 'spec/lib/scholarsphere/solr_admin_spec.rb'
    - 'spec/services/airtable_exporter_spec.rb'
    - 'spec/services/curation_task_exporter_spec.rb'

RSpec/MultipleSubjects:
  Exclude:
    - 'spec/policies/collection_policy_spec.rb'

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/components/mintable_doi_component_spec.rb'
    - 'spec/components/resource_edit_button_spec.rb'
    - 'spec/components/work_versions/version_navigation_component_spec.rb'
    - 'spec/components/work_histories/work_history_component_spec.rb'
    - 'spec/controllers/dashboard/work_search_controller_spec.rb'
    - 'spec/services/session_view_stats_cache_spec.rb'

Style/ClassVars:
  Exclude:
    - 'spec/system/active_job_system_spec.rb'

Style/EmptyMethod:
  Exclude:
    - 'app/jobs/metadata_listener/job.rb'

Lint/MissingSuper:
  Exclude:
   - 'app/models/concerns/null_object_pattern.rb'

Style/EmptyCaseCondition:
  Exclude:
    - 'app/services/doi_service.rb'
    - 'app/controllers/dashboard/form/base_controller.rb'

