terms:
  - id: DBA
    term: Doctor of Business Administration
    active: true
  - id: DED
    term: Doctor of Education
    active: true
  - id: DEng
    term: Doctor of Engineering
    active: true
  - id: DMA
    term: Doctor of Musical Arts
    active: true
  - id: DNP
    term: Doctor of Nursing Practice
    active: true
  - id: DrPH
    term: Doctor of Public Health
    active: true
