terms:
  - id: https://creativecommons.org/licenses/by/4.0/
    term: CC BY 4.0 (Attribution)
    active: true
  - id: https://creativecommons.org/licenses/by-sa/4.0/
    term: CC BY-SA 4.0 (Attribution-ShareAlike)
    active: true
  - id: https://creativecommons.org/licenses/by-nc/4.0/
    term: CC BY-NC 4.0 (Attribution-NonCommercial)
    active: true
  - id: https://creativecommons.org/licenses/by-nd/4.0/
    term: CC BY-ND 4.0 (Attribution-NoDerivatives)
    active: true
  - id: https://creativecommons.org/licenses/by-nc-nd/4.0/
    term: CC BY-NC-ND 4.0 (Attribution-NonCommercial-NoDerivatives)
    active: true
  - id: https://creativecommons.org/licenses/by-nc-sa/4.0/
    term: CC BY-NC-SA 4.0 (Attribution-NonCommercial-ShareAlike)
    active: true
  - id: http://creativecommons.org/publicdomain/zero/1.0/
    term: CC0 1.0 (Public Domain Dedication)
    active: true
  - id: https://opensource.org/licenses/MIT
    term: MIT License
    active: true
  - id: https://opensource.org/licenses/BSD-3-Clause
    term: BSD 3-Clause License
    active: true
  - id: http://www.apache.org/licenses/LICENSE-2.0
    term: Apache 2.0
    active: true
  - id: https://www.gnu.org/licenses/gpl.html
    term: GNU General Public License (GPLv3)
    active: true
  - id: https://rightsstatements.org/page/InC/1.0/
    term: In Copyright (Rights Reserved)
    active: true
  - id: https://rightsstatements.org/page/NoC-US/1.0/
    term: No Copyright - U.S.
    active: true
  - id: http://creativecommons.org/licenses/by/3.0/us/
    term: Attribution 3.0 United States
    active: false
  - id: http://creativecommons.org/licenses/by-sa/3.0/us/
    term: Attribution-ShareAlike 3.0 United States
    active: false
  - id: http://creativecommons.org/licenses/by-nc/3.0/us/
    term: Attribution-NonCommercial 3.0 United States
    active: false
  - id: http://creativecommons.org/licenses/by-nd/3.0/us/
    term: Attribution-NoDerivs 3.0 United States
    active: false
  - id: http://creativecommons.org/licenses/by-nc-nd/3.0/us/
    term: Attribution-NonCommercial-NoDerivs 3.0 United States
    active: false
  - id: http://creativecommons.org/licenses/by-nc-sa/3.0/us/
    term: Attribution-NonCommercial-ShareAlike 3.0 United States
    active: false
  - id: http://www.europeana.eu/portal/rights/rr-r.html
    term: All rights reserved
    active: false
  - id: http://creativecommons.org/publicdomain/mark/1.0/
    term: Public Domain Mark 1.0
    active: false