development:
  adapter: redis
  channel_prefix: scholarsphere_development
  password: <%= ENV.fetch("REDIS_PASSWORD", 'redispassword') %>

test:
  adapter: test

production:
  adapter: redis
  channel_prefix: scholarsphere_prod_action_cable
