development:
  adapter: redis
  url: <%= Scholarsphere::RedisConfig.new.to_hash[:url] %>
  channel_prefix: scholarsphere_development
  password: <%= ENV.fetch("REDIS_PASSWORD", 'redispassword') %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= Scholarsphere::RedisConfig.new.to_hash[:url] %>
  channel_prefix: scholarsphere_production
