:concurrency: 5
:max_retries: <%= ENV.fetch("SIDEKIQ_MAX_RETRIES", 2) %>
:queues:
  - doi
  - indexing
  - mailers
  - shrine
  - statistics
  - thumbnails
  - signature
  - accessibility_check
  - auto_remediation_out
  - auto_remediation_in
